name: Push a npm package to Cloudsmith with OIDC
on:
  push:
    branches: [ main ]
permissions:
  id-token: write      # Necessary to GH Identity Provider to write the JWT token which Cloudsmith needs to read
  contents: read

jobs:
  job:
    environment: Production
    runs-on: ubuntu-latest
    steps:
    - name: Install OIDC Client from Core Package
      run: npm install @actions/core@1.6.0 @actions/http-client
    - name: Get Id Token
      uses: actions/github-script@v6
      id: idtoken
      with:
        script: |
          const coredemo = require('@actions/core')
          let id_token = await coredemo.getIDToken()
          coredemo.setOutput('id_token', id_token)
          var xhr = new XMLHttpRequest();
          xhr.open("POST", "https://api.cloudsmith.io/openid/interview-giriraj-yadav/");
          xhr.setRequestHeader('content-Type', 'application/json');
          const body = JSON.stringify({
  service_slug: "SERVICE_ACCOUNT_SLUG",
  oidc_token: id_token
});
xhr.onload = () => {
  if (xhr.readyState == 4 && xhr.status == 201) {
    console.log(JSON.parse(xhr.responseText));
  } else {
    console.log(`Error: ${xhr.status}`);
  }
};

xhr.send("{\n  \"email\": \"xyz@example.com\",\n  \"type\": \"Secondary\"\n}");