name: Push a debian package to Cloudsmith with OIDC
on:
  push:
    branches: [ main ]
permissions:
  id-token: write      # Necessary to GH Identity Provider to write the JWT token which Cloudsmith needs to read
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    name: Push a npm package to Cloudsmith using OIDC to authenticate
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get OIDC token
        run: |

          value=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq '.value')
          echo "value=${value}" >> $GITHUB_OUTPUT
          
          token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"SERVICE_ACCOUNT_SLUG\"}" https://api.cloudsmith.io/openid/interview-giriraj-yadav/ | jq -r '.token')
          echo "$token"
          
      - name: Cloudsmith Push NPM Package
        uses: cloudsmith-io/action@v0.5.3
        with:
          command: 'push'
          format: 'npm'
          owner: 'interview-giriraj-yadav'             # Your Cloudsmith account name or org name (namespace)
          repo: 'dev'        
          republish: 'true'         
          file: 'cloudsmith-npm-example-1.0.0.tgz'  