name: Push a npm package to Cloudsmith with OIDC
on:
  push:
    branches: [ main ]
permissions:
  id-token: write      # Necessary to GH Identity Provider to write the JWT token which Cloudsmith needs to read
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    name: Push a npm package to Cloudsmith using OIDC to authenticate
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: install node
        run: npm install

      - name: build pakage
        run: zip giriraj_interview1.zip ./* -r

      - name: store build pakage
        uses: actions/upload-artifact@v1
        with:
      - name: build
        path: giriraj_interview1.zip