name: Push a debian package to Cloudsmith with OIDC
on:
  push:
    branches: [ main ]
permissions:
  id-token: write      # Necessary to GH Identity Provider to write the JWT token which Cloudsmith needs to read
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    name: Push a npm package to Cloudsmith using OIDC to authenticate
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get OIDC token

       - run: echo "Testing out OpenID Connect in GitHub Actions."
      - run: |
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq '.value')
          echo "$value"
          jwt=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"github-service\"}" https://api.cloudsmith.io/openid/interview-giriraj-yadav/ | jq -r '.token' )
          echo "OIDC token from Cloudsmith: $jwt"
          
      - name: Cloudsmith Push NPM Package
        uses: cloudsmith-io/action@v0.5.3
        with:
          command: 'push'
          format: 'deb'
          owner: 'interview-giriraj-yadav'             # Your Cloudsmith account name or org name (namespace)
          repo: 'dev'         # Your Cloudsmith Repository name (slug)
          distro: 'npm'     # Your Distribution  (i.e Debian, Ubuntu)
          release: 'buster'         # Your Distribution Release (i.e xenial, buster)
          republish: 'true'          # needed if version is not changing
          file: 'cloudsmith-npm-example-1.0.0.tgz'  # debian package filename